### ISSUE TITLE
Implement daily and hourly rewards

### ISSUE THREAD

**Issue by Emil8250** [Emil8250/SuperGamblino#5]

**Comment by KanarekLife** [comment]
Hi!
I would like to try and help you with this issue but I do need more info about how should it look like.
Currently how would I implement it is that admin setup certain ammount of credits, time in which these credits will be given (ex. every 300 seconds or 5 dats) and the max ammount of credits after which user won't receive any free credits. However, it's your project so need I some simple explanation how you see it.
Cheers.

**Comment by tenasow** [comment]
For balancing reasons the daily and hourly rewards are not going to be configurable, since it would create balancing issues, there's more things involved over this already such as leveling(not implemented yet though).

Daily rewards are available every 24th hour, and hourly rewards are available every hour passed. The base we discussed for daily is 500, and hourly 20. But this might change so hard to say at this point.

There's no point in which the daily and hourly credits won't be available to any player, the idea is we want to modify this number later on based off of levels, as the players want a feeling of progression.

**Comment by KanarekLife** [comment]
Ok. I'll sit to code then and just implement it. ;)

**Comment by Emil8250** [comment]
> Ok. I'll sit to code then and just implement it. ;)

Perfect! 
Thanks for taking interest in this fairly young project:-)

**Comment by Emil8250** [comment]
Fixed by https://github.com/Emil8250/SuperGamblino/pull/12
